//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsvAvaloniaToDoSample {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RS {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RS() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("AsvAvaloniaToDoSample.RS", typeof(RS).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string ToDoListView_ListTitle {
            get {
                return ResourceManager.GetString("ToDoListView_ListTitle", resourceCulture);
            }
        }
        
        public static string ToDoListView_Title {
            get {
                return ResourceManager.GetString("ToDoListView_Title", resourceCulture);
            }
        }
        
        public static string ToDoListView_AddNewItem {
            get {
                return ResourceManager.GetString("ToDoListView_AddNewItem", resourceCulture);
            }
        }
        
        public static string ToDoListView_RemoveItem {
            get {
                return ResourceManager.GetString("ToDoListView_RemoveItem", resourceCulture);
            }
        }
        
        public static string ToDoListCommands_AddDesc {
            get {
                return ResourceManager.GetString("ToDoListCommands_AddDesc", resourceCulture);
            }
        }
        
        public static string ToDoListCommands_RemoveDesc {
            get {
                return ResourceManager.GetString("ToDoListCommands_RemoveDesc", resourceCulture);
            }
        }
    }
}
